name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest

    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        if: github.ref == "test"
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
