name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest

    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        if: contains(github.head_ref, 'fuga')
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Dump GitHub head_ref
        run: echo github.head_ref
      - name: Dump GitHub ref
        run: echo github.ref